name: Browserstack End to End Tests
concurrency: browserstack_e2e
on:
  # schedule:
  #   - cron: '35 8 * * *'
  push:
    branches:
      # If you're seeing this, Jon forgot to remove it.
      # This is for debugging only, and this should still be a cron
      - 'bodging-browserstack'
jobs:
  browserstack_e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: td.vue
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'

      - name: Cache NPM dir
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.OS }}-pnpm-cache-server-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm-cache-server-

      - name: Install pnpm
        run: npm i -g pnpm

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: BrowserStack Env Setup
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: Run e2e tests
        run: npm run test:e2e-nightly
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
